version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.28
    restart: always
    ports:
    - "4466:4466"
    environment:
      APP_DOMAIN: gp.docker
      VIRTUAL_HOST: .gp.docker
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            schema: maps
            database: maps
            user: admin
            password: ${PASSWORD}
            rawAccess: true
            port: '5432'
            migrations: false

    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
    - "5434:5432"
    environment:
      VIRTUAL_HOST: psql.gp.docker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${PASSWORD}